queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Misc tests (checks)
      - status-success=Misc tests (licenses)
      - status-success=Unit tests (py36-unittest)
      - status-success=Unit tests (py37-unittest)
      - status-success=Unit tests (py38-unittest)
      - status-success=Unit tests (py39-unittest)
      - status-success=Integration tests (3.6)
      - status-success=Integration tests (3.7)
      - status-success=Integration tests (3.8)
      - status-success=Integration tests (3.9)

pull_request_rules:
  - name: default
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: none
    conditions:
      - label!=no-mergify
      - approved-reviews-by=@fedora-infra/fedora-messaging-maintainers
      - status-success=DCO
      - status-success=Misc tests (checks)
      - status-success=Misc tests (licenses)
      - status-success=Unit tests (py36-unittest)
      - status-success=Unit tests (py37-unittest)
      - status-success=Unit tests (py38-unittest)
      - status-success=Unit tests (py39-unittest)
      - status-success=Integration tests (3.6)
      - status-success=Integration tests (3.7)
      - status-success=Integration tests (3.8)
      - status-success=Integration tests (3.9)
  - name: default-from-fedora-messaging-team
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: none
    conditions:
      - label!=no-mergify
      - author=@fedora-infra/fedora-messaging-maintainers
      - "#approved-reviews-by>=1"
      - status-success=DCO
      - status-success=Misc tests (checks)
      - status-success=Misc tests (licenses)
      - status-success=Unit tests (py36-unittest)
      - status-success=Unit tests (py37-unittest)
      - status-success=Unit tests (py38-unittest)
      - status-success=Unit tests (py39-unittest)
      - status-success=Integration tests (3.6)
      - status-success=Integration tests (3.7)
      - status-success=Integration tests (3.8)
      - status-success=Integration tests (3.9)
